---
- name: Ensure HAProxy is installed.
  package: name=haproxy state=present
  tags: [ install ]

- name: Ensure HAProxy is enabled (so init script will start it on Debian).
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when: ansible_os_family == 'Debian'
  tags: [ install ]

- name: Copy HAProxy configuration in place.
  template:
    src: '{{ haproxy_template }}'
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c
  notify: restart haproxy
  tags: [ install, config ]

- name: Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes
  tags: [ install, config ]
